name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Generate appsettings.json
      run: |
       echo "$APPSETTINGS_JSON" > ./ArenaRESTTests/bin/Debug/net8.0/appsettings.json
       env:
       APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_JSON }}

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build
      run: dotnet build --configuration Debug

    # Run tests
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hovedopgteamet' 
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './bin/Release/net7.0/publish'  
