name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for clean state
          
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

  

      - name: Clean
        run: dotnet clean && dotnet nuget locals all --clear
        
      - name: Restore
        run: dotnet restore --force
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hovedopgteamet'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './bin/Release/net8.0/publish'
