name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_JSON }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - name: Test
        run: dotnet test
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hovedopgteamet'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './ArenaREST/bin/Debug/net8.0'
